In [1]:
import pandas as pd
import numpy as np

In [6]:
from re import T
a = [1, 3, 4, 5, 6, 7, 8, 10, 13, 16, 0, 6, 8, 2]
serise_a = pd.Series(a)
print(type(serise_a),"\n", serise_a.sort_values(ascending = True))

<class 'pandas.core.series.Series'>
 10     0
0      1
13     2
1      3
2      4
3      5
4      6
11     6
5      7
6      8
12     8
7     10
8     13
9     16
dtype: int64

In [7]:
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
energy_df=pd.DataFrame(data=data)
print(energy_df)

  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

In [8]:
# Impute missing values in 'Energy Consumption (MWh)' with the mean

energy_df.iloc[:, 1] = energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean())

# Impute missing values in 'Cost (Million $)' with the mean

energy_df.iloc[:, 2] = energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean())

print("\nData After Imputing Missing Values with Mean:")

print(energy_df)

Data After Imputing Missing Values with Mean:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0             250.0

In [19]:
import pandas as pd
import numpy as np
from google.colab import files

In [20]:
uploaded = files.upload()

Saving owid-co2-data.csv to owid-co2-data (1).csv

In [22]:
df = pd.read_csv("owid-co2-data.csv")
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
print(df.shape)
print(df.columns)
print(df.info())
df.describe()

(50411, 79)
Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50411 entries, 0 to 50410
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50411 non-null  object
 1   year                                       50411 non-null  int64
 2   iso_code                                   42480 non-null  object
 3   population                                 41167 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 29173 non-null  float64
 6   cement_co2_per_capita                      25648 non-null  float64
 7   co2                                        29384 non-null  float64
 8   co2_growth_abs                             27216 non-null  float64
 9   co2_growth_prct                            26239 non-null  float64
 10  co2_including_luc                          23796 non-null  float64
 11  co2_including_luc_growth_abs               23496 non-null  float64
 12  co2_including_luc_growth_prct              23496 non-null  float64
 13  co2_including_luc_per_capita               23757 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          10133 non-null  float64
 16  co2_per_capita                             26509 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10826 non-null  float64
 19  coal_co2                                   21925 non-null  float64
 20  coal_co2_per_capita                        21314 non-null  float64
 21  consumption_co2                            5053 non-null   float64
 22  consumption_co2_per_capita                 4643 non-null   float64
 23  consumption_co2_per_gdp                    4448 non-null   float64
 24  cumulative_cement_co2                      29151 non-null  float64
 25  cumulative_co2                             27563 non-null  float64
 26  cumulative_co2_including_luc               23796 non-null  float64
 27  cumulative_coal_co2                        21925 non-null  float64
 28  cumulative_flaring_co2                     16111 non-null  float64
 29  cumulative_gas_co2                         18147 non-null  float64
 30  cumulative_luc_co2                         37450 non-null  float64
 31  cumulative_oil_co2                         25458 non-null  float64
 32  cumulative_other_co2                       3254 non-null   float64
 33  energy_per_capita                          10586 non-null  float64
 34  energy_per_gdp                             7787 non-null   float64
 35  flaring_co2                                16174 non-null  float64
 36  flaring_co2_per_capita                     14910 non-null  float64
 37  gas_co2                                    18147 non-null  float64
 38  gas_co2_per_capita                         17446 non-null  float64
 39  ghg_excluding_lucf_per_capita              35842 non-null  float64
 40  ghg_per_capita                             36179 non-null  float64
 41  land_use_change_co2                        37450 non-null  float64
 42  land_use_change_co2_per_capita             36635 non-null  float64
 43  methane                                    38150 non-null  float64
 44  methane_per_capita                         36179 non-null  float64
 45  nitrous_oxide                              38500 non-null  float64
 46  nitrous_oxide_per_capita                   36439 non-null  float64
 47  oil_co2                                    25459 non-null  float64
 48  oil_co2_per_capita                         24722 non-null  float64
 49  other_co2_per_capita                       2659 non-null   float64
 50  other_industry_co2                         3254 non-null   float64
 51  primary_energy_consumption                 10631 non-null  float64
 52  share_global_cement_co2                    22270 non-null  float64
 53  share_global_co2                           27563 non-null  float64
 54  share_global_co2_including_luc             23796 non-null  float64
 55  share_global_coal_co2                      21925 non-null  float64
 56  share_global_cumulative_cement_co2         22270 non-null  float64
 57  share_global_cumulative_co2                27563 non-null  float64
 58  share_global_cumulative_co2_including_luc  23796 non-null  float64
 59  share_global_cumulative_coal_co2           21925 non-null  float64
 60  share_global_cumulative_flaring_co2        11089 non-null  float64
 61  share_global_cumulative_gas_co2            15167 non-null  float64
 62  share_global_cumulative_luc_co2            37450 non-null  float64
 63  share_global_cumulative_oil_co2            23833 non-null  float64
 64  share_global_cumulative_other_co2          2170 non-null   float64
 65  share_global_flaring_co2                   11089 non-null  float64
 66  share_global_gas_co2                       15167 non-null  float64
 67  share_global_luc_co2                       37450 non-null  float64
 68  share_global_oil_co2                       23833 non-null  float64
 69  share_global_other_co2                     2170 non-null   float64
 70  share_of_temperature_change_from_ghg       41238 non-null  float64
 71  temperature_change_from_ch4                38280 non-null  float64
 72  temperature_change_from_co2                41238 non-null  float64
 73  temperature_change_from_ghg                41238 non-null  float64
 74  temperature_change_from_n2o                38280 non-null  float64
 75  total_ghg                                  38150 non-null  float64
 76  total_ghg_excluding_lucf                   37813 non-null  float64
 77  trade_co2                                  4712 non-null   float64
 78  trade_co2_share                            4712 non-null   float64
dtypes: float64(76), int64(1), object(2)
memory usage: 30.4+ MB
None

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50411.000000,4.116700e+04,1.525100e+04,29173.000000,25648.000000,29384.000000,27216.000000,26239.000000,23796.000000,23496.000000,...,2170.000000,41238.000000,38280.000000,41238.000000,41238.000000,3.828000e+04,38150.000000,37813.000000,4712.000000,4712.000000
mean,1920.349249,6.017294e+07,3.300495e+11,7.890110,0.060026,420.227031,6.268844,42.598225,544.144590,7.483698,...,7.190606,2.272248,0.002913,0.008048,0.011256,5.432353e-04,490.799605,310.521462,-6.986785,21.468644
std,65.859123,3.308412e+08,3.086383e+12,62.988172,0.123567,1972.092036,62.199549,1721.913018,2273.281695,99.512520,...,17.448984,9.282339,0.015353,0.045680,0.062882,3.041013e-03,2414.076754,1812.363568,259.018190,62.637597
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1928.339478,-100.000000,-84.560249,-2298.978271,...,0.000000,-0.823860,-0.000866,-0.000067,-0.000613,0.000000e+00,-19.725241,0.000073,-2177.807373,-98.281097
25%,1875.000000,3.272140e+05,7.874038e+09,0.000000,0.000000,0.381056,-0.004662,-1.070526,6.667555,-0.727634,...,0.143816,0.003304,0.000004,0.000002,0.000006,8.399180e-07,1.501726,0.220689,-2.261994,-6.829136
50%,1925.000000,2.291264e+06,2.743861e+10,0.000000,0.001018,5.080755,0.043968,3.813481,28.119772,0.111709,...,0.588111,0.081103,0.000060,0.000116,0.000192,1.061610e-05,14.605876,2.221920,1.640741,8.381797
75%,1975.000000,9.986553e+06,1.212627e+11,0.523760,0.076579,53.656342,1.018214,10.884243,124.303370,2.764908,...,2.416414,0.373046,0.000490,0.000947,0.001512,8.899588e-05,76.508112,27.862854,11.425750,32.781820
max,2024.000000,8.161973e+09,1.301126e+14,1666.885010,2.483903,38598.578125,1804.656616,180870.000000,43184.085938,2614.874023,...,100.000008,100.000000,0.376540,1.216369,1.678361,8.545313e-02,54433.398438,43714.777344,1768.846313,1023.042358

In [24]:
df.isnull().sum()

country                            0
year                               0
iso_code                        7931
population                      9244
gdp                            35160
                               ...
temperature_change_from_n2o    12131
total_ghg                      12261
total_ghg_excluding_lucf       12598
trade_co2                      45699
trade_co2_share                45699
Length: 79, dtype: int64

In [25]:
numeric_columns = df.select_dtypes(include=np.number).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

text_columns = df.select_dtypes(include="object").columns
df[text_columns] = df[text_columns].fillna("Unknown")

df.isnull().sum()

country                        0
year                           0
iso_code                       0
population                     0
gdp                            0
                              ..
temperature_change_from_n2o    0
total_ghg                      0
total_ghg_excluding_lucf       0
trade_co2                      0
trade_co2_share                0
Length: 79, dtype: int64

In [26]:
df.corr(numeric_only=True)

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
year,1.000000,0.062337,0.028764,0.096069,0.221854,0.093273,0.027354,-0.005754,0.037400,0.003926,...,-0.000216,-0.002566,0.108798,0.106439,0.108255,0.114631,0.093160,0.103376,0.000485,0.006602
population,0.062337,1.000000,0.387132,0.789213,0.051635,0.696023,0.500357,-0.004786,0.877709,0.313799,...,0.628458,0.658647,0.877290,0.765870,0.801023,0.815859,0.862979,0.801316,-0.244198,-0.080655
gdp,0.028764,0.387132,1.000000,0.477128,0.064514,0.377388,0.171031,-0.001717,0.415113,0.073946,...,0.412371,0.200435,0.398457,0.409395,0.411332,0.433083,0.387896,0.410785,-0.036850,-0.040352
cement_co2,0.096069,0.789213,0.477128,1.000000,0.152656,0.754774,0.506743,-0.002764,0.844803,0.291260,...,0.736644,0.408628,0.804096,0.732627,0.758073,0.781656,0.804102,0.837197,-0.410603,-0.087599
cement_co2_per_capita,0.221854,0.051635,0.064514,0.152656,1.000000,0.108074,0.063381,-0.009010,0.089737,0.027121,...,-0.006807,0.009743,0.093616,0.101942,0.101259,0.099092,0.098251,0.127733,-0.028894,-0.087727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
temperature_change_from_n2o,0.114631,0.815859,0.433083,0.781656,0.099092,0.768060,0.408158,-0.004683,0.899506,0.244111,...,0.713130,0.652259,0.970015,0.980863,0.987313,1.000000,0.955210,0.962827,-0.029834,-0.085809
total_ghg,0.093160,0.862979,0.387896,0.804102,0.098251,0.781346,0.494769,-0.005166,0.948928,0.309540,...,0.678440,0.773810,0.983889,0.958056,0.971926,0.955210,1.000000,0.977239,-0.151825,-0.081593
total_ghg_excluding_lucf,0.103376,0.801316,0.410785,0.837197,0.127733,0.799687,0.474636,-0.004523,0.924293,0.280438,...,0.723906,0.676026,0.964190,0.966477,0.973764,0.962827,0.977239,1.000000,-0.139592,-0.080840
trade_co2,0.000485,-0.244198,-0.036850,-0.410603,-0.028894,-0.119819,-0.321924,-0.000219,-0.156055,-0.183927,...,-0.090747,-0.016060,-0.142750,0.004288,-0.031856,-0.029834,-0.151825,-0.139592,1.000000,0.127991
trade_co2_share,0.006602,-0.080655,-0.040352,-0.087599,-0.087727,-0.071745,-0.043765,-0.000107,-0.083554,-0.025809,...,-0.081897,-0.043381,-0.088825,-0.077879,-0.081460,-0.085809,-0.081593,-0.080840,0.127991,1.000000