In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [8]:
uploaded = files.upload()

Saving owid-energy-codebook.csv to owid-energy-codebook (1).csv

In [9]:

energy_df=pd.read_csv("owid-energy-codebook.csv")
energy_df

,column,title,description,unit,source
0,country,Country,Geographic location.,NaN,Our World in Data - Regions (2025)
1,year,Year,Year of observation.,NaN,Our World in Data - Regions (2025)
2,iso_code,ISO code,ISO 3166-1 alpha-3 three-letter country codes.,NaN,International Organization for Standardization...
3,population,Population,"Population by country, available from 10,000 B...",people,Population based on various sources (2024) [ht...
4,gdp,Gross domestic product (GDP),Total economic output of a country or region p...,international-$ in 2011 prices ($),Bolt and van Zanden – Maddison Project Databas...
...,...,...,...,...,...
125,wind_elec_per_capita,Electricity generation from wind power per person,Measured in kilowatt-hours per person.,kilowatt-hours (kWh),Ember - Yearly Electricity Data Europe (2026) ...
126,wind_electricity,Electricity generation from wind power,Measured in terawatt-hours.,terawatt-hours (TWh),Ember - Yearly Electricity Data Europe (2026) ...
127,wind_energy_per_capita,Wind power consumption per capita,Measured in kilowatt-hours per person.,kilowatt-hours (kWh),Energy Institute - Statistical Review of World...
128,wind_share_elec,Share of electricity generated by wind power,Measured as a percentage of total electricity ...,%,Ember - Yearly Electricity Data Europe (2026) ...
129,wind_share_energy,Share of primary energy consumption that comes...,Measured as a percentage of the total primary ...,%,Energy Institute - Statistical Review of World...

In [10]:

energy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   column       130 non-null    object
 1   title        130 non-null    object
 2   description  118 non-null    object
 3   unit         127 non-null    object
 4   source       130 non-null    object
dtypes: object(5)
memory usage: 5.2+ KB

In [11]:

energy_df.shape

(130, 5)

In [12]:

energy_df.isnull().sum()

column          0
title           0
description    12
unit            3
source          0
dtype: int64

In [13]:

energy_df.isnull().sum()

column          0
title           0
description    12
unit            3
source          0
dtype: int64

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [22]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
uploaded = files.upload()

In [ ]:
import pandas as pd

df = pd.read_csv(
    "API_EN.ATM.CO2E,KT_DS2_en_csv_v2_5352590.csv.csv",
    skiprows=4
)

df.head()

In [ ]:
print(df.shape)

print(df.info())

print(df.describe())

print(df.isnull().sum())

In [ ]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [ ]:
df.rename(columns={'Country Name': 'Country',
                   '2020': 'CO2_Emission'}, inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

X = df[['CO2_Emission']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)

df['Cluster'] = kmeans.fit_predict(X_scaled)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

sns.scatterplot(
    x=df.index,
    y='CO2_Emission',
    hue='Cluster',
    data=df,
    palette='viridis'
)

plt.title("CO₂ Emission Clusters")
plt.xlabel("Countries")
plt.ylabel("CO₂ Emission")
plt.show(